---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: entity
  labels:
    provider: vault
spec:
  compositeTypeRef:
    apiVersion: kundun.dev/v1alpha1
    kind: Entity
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - name: userpass-mount
        base:
          apiVersion: auth.vault.upbound.io/v1alpha1
          kind: Backend
          spec:
            forProvider:
              path: userpass
              type: userpass
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.accessor
          toFieldPath: status.userPassAccessor
      - name: policy
        base:
          apiVersion: vault.vault.upbound.io/v1alpha1
          kind: Policy
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.policy.name
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.policy.paths
          toFieldPath: spec.forProvider.policy
      - name: user
        base:
          apiVersion: generic.vault.upbound.io/v1alpha1
          kind: Endpoint
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.userFieldsJsonSecretRef
          toFieldPath: spec.forProvider.dataJsonSecretRef
        - type: FromCompositeFieldPath
          fromFieldPath: spec.username
          toFieldPath: spec.forProvider.path
          transforms:
          - type: string
            string:
              fmt: "auth/userpass/users/%s"
              type: Format
      - name: entity
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: Entity
          spec:
            forProvider:
              disabled: false
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.username
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.metadata
          toFieldPath: spec.forProvider.metadata
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.entityId
      - name: entityAlias
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: EntityAlias
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.username
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: status.userPassAccessor
          toFieldPath: spec.forProvider.mountAccessor
        - type: FromCompositeFieldPath
          fromFieldPath: status.entityId
          toFieldPath: spec.forProvider.canonicalId
      - name: group
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: Group
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: status.entityId
          toFieldPath: spec.forProvider.memberEntityIds
          transforms:
            - type: string
              string:
                type: Format
                fmt: '[ "%s" ]'
            - type: convert
              convert:
                toType: array
                format: json