---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: oidc
  labels:
    provider: vault
spec:
  compositeTypeRef:
    apiVersion: kundun.dev/v1alpha1
    kind: OIDC
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - name: assignment
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcAssignment
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
        # - type: FromCompositeFieldPath
        #   fromFieldPath: spec.groupIds
        #   toFieldPath: spec.forProvider.groupIds
        # - type: FromCompositeFieldPath
        #   fromFieldPath: spec.entityIds
        #   toFieldPath: spec.forProvider.entityIds
      - name: key
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcKey
          spec:
            forProvider:
              allowedClientIds:  [ "*" ]
              rotationPeriod: 3600
              verificationTtl: 7200
              algorithm: RS256
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
      - name: client
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcClient
          spec:
            forProvider:
              idTokenTtl: 1800
              accessTokenTtl: 3600
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.key
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.assignments
          transforms:
            - type: string
              string:
                type: Format
                fmt: '[ "%s" ]'
            - type: convert
              convert:
                toType: array
                format: json
        - fromFieldPath: spec.redirectUris
          toFieldPath: spec.forProvider.redirectUris
      - name: provider
        base:
          apiVersion: identity.vault.upbound.io/v1alpha1
          kind: OidcProvider
        patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
        - fromFieldPath: spec.scopesSupported
          toFieldPath: spec.forProvider.scopesSupported

