---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ssh
  labels:
    provider: vault
spec:
  compositeTypeRef:
    apiVersion: kundun.dev/v1alpha1
    kind: SSH
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    step: patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      resources:
      - name: ssh-mount
        base:
          apiVersion: vault.vault.upbound.io/v1alpha1
          kind: Mount
          spec:
            forProvider:
              path: ssh
              type: ssh
        patches:
        - type: PatchSet
          patchSetName: metadata
      - name: ca
        base:
          apiVersion: ssh.vault.upbound.io/v1alpha1
          kind: SecretBackendCA
          spec:
            forProvider:
              backendRef:
                name: ssh
              generateSigningKey: true
        patches:
        - type: PatchSet
          patchSetName: metadata
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.publicKey
          toFieldPath: status.caPublicKey
      - name: role-ca
        base:
          apiVersion: ssh.vault.upbound.io/v1alpha1
          kind: SecretBackendRole
          spec:
            forProvider:
              backendRef:
                name: ssh
              keyType: ca
              algorithmSigner: rsa-sha2-256
              allowUserCertificates: true
              allowedUsers: "*"
              allowedExtensions: "permit-pty,permit-port-forwarding" 
              defaultExtensions:
                permitPty: ""
              ttl: 30m
        patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: "%s-ca"
              type: Format
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
          transforms:
          - type: string
            string:
              fmt: "%s-ca"
              type: Format
        - type: FromCompositeFieldPath
          fromFieldPath: spec.defaultUser
          toFieldPath: spec.forProvider.defaultUser
      - name: role-otp
        base:
          apiVersion: ssh.vault.upbound.io/v1alpha1
          kind: SecretBackendRole
          spec:
            forProvider:
              backendRef:
                name: ssh
              keyType: otp
              cidrList: "0.0.0.0/0"
        patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: "%s-otp"
              type: Format
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
          transforms:
          - type: string
            string:
              fmt: "%s-otp"
              type: Format
        - type: FromCompositeFieldPath
          fromFieldPath: spec.defaultUser
          toFieldPath: spec.forProvider.defaultUser
