apiVersion: kundun.dev/v1alpha1
kind: PKIClaim
metadata:
  name: my-pki
  namespace: test
spec:
  id: pki
  commonNamePrefix: Local
  ouPrefix: Local
  organization: Local doo
  locality: Belgrade
  province: Serbia
  country: SR
  compositionSelector:
    matchLabels:
      provider: vault
---
apiVersion: pki.vault.upbound.io/v1alpha1
kind: SecretBackendCert
metadata:
  name: my-pki-cert
  namespace: test
spec:
  forProvider:
    backendRef: 
      name: pki-int
    nameRef: 
      name: pki-int
    commonName: vault.com
    ipSans: [ "172.16.1.11","172.16.1.12","172.16.1.13" ]
    altNames: [ "*.vault.com" ]